function fprint(name, first, second) 
    if contains(name, 'haft')
        fprintf(['Shaft vibration calculation is done', ...
            '(%s, %d-%d signals) \n'], ... 
            name, first, second);
    elseif contains(name, 'ore')
        fprintf(['Stator core vibration calculation is done', ...
            '(%s, %d-%d signals) \n'], ... 
            name, first, second);
    else
        fprintf(['Vibration calculation is done ', ...
            '(%s, %d-%d signals) \n'], ...
            name, first, second);  
    end
end