function [modes, exfile, folder, nametable, pairsignal] = ratedvalue(list)

modes = {'XXT 80%n_í','XXT 90%n_í','XXT 100%n_í','XXT 110%n_í', ...
         'XXÃ 100%U_í',...
         '0 ÌÂò', '12 ÌÂò', '20 ÌÂò','30 ÌÂò','40 ÌÂò','50 ÌÂò','60 ÌÂò'};
     
exfile = {'80%n'; '90%n'; '100%n'; '110%n'; ...
          '100%U'; ...
          '0MW'; '12MW'; '20MW'; '30MW'; '40MW'; '50MW'; '60MW'};
      
nametable = {'GeneratorShaft', 'TurbineShaft', 'GB', 'TB', 'StatorCore', 'BearingSupport', 'TurbineCover'};      
      
folder = {'Generator shaft HR/'; 'Generator shaft RB/'; ...
          'Turbine shaft HR/'; 'Turbine shaft RB/'; ...
          'GB-HR/'; 'GB-RB/'; ...
          'TB-HR/'; 'TB-RB/'; ...
          'Stator core HR/'; ...
          'Stator core RB/'; ...
          'Bearing support/'; ...
          'Turbine cover/'};
      
%folder = list{1};
% Signal pair, where 1 is one signal of measure zone, 2 is two signals of measure zone
pairsignal = [2 2 2 2 2 1 1];  
      
end