function opt = calculatePeaksSpline(opt)
    
    [timePeaks,valuePeaks] = findPeaksNils(opt);
    
    timeSpline = (opt.startTime:opt.splineTime:opt.endTime)';   
    [~,ind] = unique(timePeaks);
    valueSpline = interp1(timePeaks(ind), ...
        valuePeaks(ind),timeSpline,'pchip');
    valueFiltered = smooth(valueSpline,opt.nFilter,'lowess');
    out = struct('initialFiltered', initialFiltered, ...
        'timePeaks', timePeaks, ...
        'valuePeaks', valuePeaks, ...
        'timeSpline', timeSpline, ...
        'valueSpline', valueSpline, ...
        'valueFiltered', valueFiltered);   
    
end