function data = bpfilter(data, order, hpf1, hpf2, fs)
    bpfilt = designfilt('bandpassiir', ...
        'FilterOrder', order, ...
        'HalfPowerFrequency1', hpf1, ...
        'HalfPowerFrequency2', hpf2, ...
        'SampleRate', fs);
    data = filter(bpfilt, data);
end