function addtext(table, name)
    text(deg2rad(table.PhaseAmp), table.DoubleAmp, ...
        [repmat([name ':'], height(table), 1), ...
        num2str(table.Mass,'%0.1f'), ...
        repmat('/', height(table), 1), ...
        num2str(table.PhaseMass,'%-1.0f')], ...
        'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'bottom', 'FontSize', 8);
% 	for i =1:height(table)
%         annotation('TextArrow', [table(i,:).x table(i,:).x], ...
%             [table(i,:).y table(i,:).y], 'String', ...
%             [name, ':', num2str(table(i,:).Mass,'%0.1f'), ...
%             '/', num2str(table(i,:).PhaseMass, '%-1.0f')], ...
%             'HeadStyle','none');
% 	end
end
